#!/bin/sh

# Check to see if there's a wired connection
CONNTYPE=$(nmcli -a | grep 'Wired connection' | sed 's/.*//')

# If there's not, check for wifi connection
if [ "$CONNTYPE" = "" ]; then
	CONNTYPE=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | sed 's/.*//')
fi

# If there's no internet connection, display exclamation marks
if [ "$CONNTYPE" = "" ]; then
	CONNAME="  /  "
fi

# Check for private ip
PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}' | cut -d '/' -f 1)

# Print the result
printf "$CONNTYPE $PRIVATE"
