#!/bin/sh

# Check to see if there's a wired connection
CONNAME=$(nmcli -a | grep 'Wired connection' | sed 's/.*//')

# If there's not, check for wifi connection
if [ "$CONNAME" = "" ]; then
	CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | sed 's/.*//')
fi

# If there's no connection, display explamation marks
if [ "$CONNAME" = "" ]; then
	CONNAME="  /  "
fi

# Check for private ip
PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}' | cut -d '/' -f 1)

# Print the result
printf "$CONNAME $PRIVATE"
