#!/bin/sh

# Check if the audio is muted. If it is, display a muted speaker.
[ $(pamixer --get-mute) = true ] && echo  && exit

# Otherwise, print a speaker and the volume per cent.
printf " $(pamixer --get-volume)%%"
