#!/bin/sh

autodisplay # Adjust screen(s)
autolight & # Adjust nightlight
autobrightness & # Adjust screen brightness
xrdb $HOME/.config/x11/xresources # Load Xresources colors
setbg # Set desktop background
pgrep -x xcompmgr > /dev/null || xcompmgr & # Compositor
pgrep -x startdunst > /dev/null || startdunst & # Notification daemon
#pgrep -x unclutter > /dev/null || unclutter --timeout 3 & # Hide cursor
#pgrep -x mpd > /dev/null || mpd & # Music player daemon
#xset s 600 # Lockscreen timeout
#pgrep -x xss-lock > /dev/null || xss-lock -- lockscreen & # Lock the screen upon idle
setxkbmap hu # Change keyboard layout to Hungarian
setxkbmap -option caps:swapescape & # Swap Capslock with Escape
transmission-daemon & # Start torrent daemon

#pgrep -x sxhkd > /dev/null || sxhkd & # Hotkey daemon
grep -x dwmblocks > /dev/null || dwmblocks & # Status bar
startdwm # Window manager
