#!/bin/sh

autodisplay
autolight &
autobrightness &
# xrdb ~/.config/x11/xresources
setbg &
pgrep -x xcompmgr > /dev/null || xcompmgr &
pgrep -x startdunst > /dev/null || startdunst &
pgrep -x unclutter > /dev/null || unclutter --timeout 3 &
pgrep -x mpd > /dev/null || mpd &
xset s 300
pgrep -x xss-lock > /dev/null || xss-lock -- lockscreen &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dwmblocks > /dev/null || dwmblocks &
startdwm
