#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb ~/.config/X11/Xresources
setbg &
$HOME/.config/polybar/launch.sh
picom &
xsetroot -cursor_name left_ptr &
setxkbmap hu &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width                  2
bspc config window_gap                    16
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bsp-layout set tall 1 --master-size 0.5
bsp-layout set tall 2 --master-size 0.5
bsp-layout set tall 3 --master-size 0.5
bsp-layout set tall 4 --master-size 0.5
bsp-layout set tall 5 --master-size 0.5
bsp-layout set tall 6 --master-size 0.5
bsp-layout set tall 7 --master-size 0.5
bsp-layout set tall 8 --master-size 0.5
bsp-layout set tall 9 --master-size 0.5
bsp-layout set tall 10 --master-size 0.5

#bspc config normal_border_color		  "#30302f"
#bspc config active_border_color	          "#474645"
#bspc config focused_border_color          "#817f7f"
#bspc config presel_feedback_color         "#f4d775" 

bspc config normal_border_color		  "$(xrdb -query | grep background | cut -f 2)"
bspc config active_border_color	          "$(xrdb -query | grep foreground | cut -f 2)"
bspc config focused_border_color          "$(xrdb -query | grep foreground | cut -f 2)"
bspc config presel_feedback_color         "#f4d775" 

bspc rule -a Alacritty:floatterm state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
