#! /bin/sh

# Startup
sxhkd &
feh --bg-scale ~/.wallpapers/black.png &

# Dual monitor setup
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-1 -s eDP-1
bspc monitor -f primary

# Single monitor setup
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Workspace rules
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Steam desktop='^5' state=floating focus=on
bspc rule -a discord desktop='^6' follow=off focus=off
bspc rule -a vlc desktop='^7' follow=on
bspc rule -a Gimp-2.10 desktop='^8' follow=on focus=on
bspc rule -a feh desktop='^8' follow=on focus=on
bspc rule -a qBittorrent desktop='^9' focus=on
bspc rule -a Virt-manager desktop='^10'focus=on

# General config
bspc config border_width          2
bspc config window_gap            8
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding		  25
bspc config bottom_padding	  0
bspc config left_padding	  0
bspc config right_padding	  0
bspc config click_to_focus        true
bspc config focus_follows_pointer false
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
