#!/bin/sh

# Specify screenshot location
#export screenshot="/tmp/screen.png"
# Specify lockscreen command
#export lockscreen="i3lock -e -f -c 000000 -i $screenshot"

# Check if the screen.png lockscreen file exists
# if it does, lock the screen with it.
#if [ -f $screenshot ]; then
#	$lockscreen
# if it doesn't, make it and lock the screen.
#else
#	maim /tmp/screen.png &&
#  	convert /tmp/screen.png -blur 0x8 /tmp/screen.png &&
#	$lockscreen
#fi

maim /tmp/screen.png
convert /tmp/screen.png -blur 0x6 /tmp/screen.png
i3lock -e -f -c 000000 -i /tmp/screen.png
